// Code generated by github.com/kyledinh/btk-cli-go (btk-cli) version 0.0.3-8b87b16 DO NOT EDIT.

package model 

import (
	_ "bytes"
	_ "encoding/json"
	_ "errors"
	_ "fmt"

	_ "github.com/google/uuid"
)

type Error struct {

	 Code int32 `json:"code"` 
	 Message string `json:"message"` 
	
}
