// Code generated by github.com/kyledinh/btk-cli-go (btk-cli) version 0.0.4-89392c9-dirty 
// DO NOT EDIT. Edit in specs/petstore.1.0.0.yaml 1.0.0 then rerun generator.

package model 

import (
	_ "github.com/pkg/errors"
	"github.com/google/uuid"
	
)

type Pet struct {

	Id uuid.UUID `json:"id"` 
	Name string `json:"name"` 
	Tag string `json:"tag"` 
	
}
