// Code generated by github.com/kyledinh/btk-cli-go (btk-cli) version 0.0.2-19a08e2-dirty DO NOT EDIT.

package model 

import (
	_ "bytes"
	_ "encoding/json"
	_ "errors"
	_ "fmt"

	_ "github.com/google/uuid"

)

type NewPet struct {

}
