// Code generated by github.com/kyledinh/btk-cli-go (btk-cli) version 0.0.4-89392c9-dirty 
// DO NOT EDIT. Edit in specs/petstore.1.0.0.yaml 1.0.0 then rerun generator.

package model 

import (
	_ "github.com/pkg/errors"
	
)

type Error struct {

	Code int32 `json:"code"` 
	Message string `json:"message"` 
	
}
