// Code generated by github.com/kyledinh/btk-cli-go (btk-cli) version 0.0.3-8b87b16 DO NOT EDIT.

package model 

import (
	_ "bytes"
	_ "encoding/json"
	_ "errors"
	_ "fmt"

	_ "github.com/google/uuid"
)

type Pet struct {

	 Id uuid.UUID `json:"id"` 
	 Name string `json:"name"` 
	 Tag string `json:"tag"` 
	
}
